# Site settings
title: 18MR
email: info@18mr.org
description: > # this means to ignore newlines until "baseurl:"
  Activating Asian America
baseurl: "" 
url: "http://action.18mr.org" # the base hostname & protocol for your site
twitter_username: 18millionrising
github_username: 18mr
github_projectname: action
facebook_url:  'http://facebook.com/18MillionRising.org'

# Build settings
markdown: kramdown

permalink: title
paginate: 9